### PR TITLE
Add real8 support to CMake

### PR DESCRIPTION
**Pull request by letmaik**
Implements #11.

This needs some more testing.

### CODE REVIEW

**Comment by dmey** [comment]
That's fine -- I will look at this once #9 is in.

**Review by dmey — APPROVED** [review]
OK with me. Conditional to full checks passing after #9 is merged in.

**Comment by dmey** [comment]
We should add at least build tests for this as well before merging this in.

**Comment by letmaik** [comment]
I enabled build tests via Travis CI and Appveyor, where half of the configurations now build with USE_REAL8=1. This prevents adding another dimension to Azure Pipelines where we already have a lot of jobs.

Given the comments in #11, we should probably in the README change
> |`USE_REAL8`|`ON`, `OFF`|`OFF`|Whether to use 8-byte reals|

to 
> |`USE_REAL8`|`ON`, `OFF`|`OFF`|Whether to use double precision reals|

I would still keep the name `USE_REAL8` simply to be in line with what WRF does (`-r8`). But I'm open to suggestions. It could also be `USE_DP` for example.

Or we leave it as it is since we don't support platforms/compilers where real8 is not actually 8-byte reals...

**Comment by dmey** [comment]
> Or we leave it as it is since we don't support platforms/compilers where real8 is not actually 8-byte reals...

I'd leave the flag as is but I am OK with change in docs to `|USE_REAL8|ON, OFF|OFF|Whether to use double precision reals|`

**Comment by letmaik** [comment]
Done. Let's target this feature for 4.1.1. So, *do not merge* until WRF-CMake 4.1 is released.

**Comment by dmey** [comment]
Agree -- added to 4.1.1 milestone to make it easier to track.

**Comment by dmey** [comment]
4.1.1 and 4.1.2 have been released -- do you still want to merge this in? Do we need to create releases? We can just wait for 4.2.0 otherwise...

**Comment by letmaik** [comment]
I'll merge it once CI passed. Please open a separate issue if you want to discuss updating to a new WRF version.

**Pull request merged**
